gems: [jekyll-paginate, jekyll-sitemap]

# Site settings
title: Блог Fora Soft о разработке мультимедиа приложений
email: info@fora-soft.com
description: > # this means to ignore newlines until "baseurl:"
 Блог компании Fora Soft.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://forasoft.github.io" # the base hostname & protocol for your site
twitter_username: forasoft

JB:
  version: 0.3.0

footer-links:
  email: info@fora-soft.com
  facebook: ForaSoft
  github: forasoft
  instagram: fora_soft
  linkedin: fora-soft-llc-
  twitter: forasoft

google_analytics: UA-69516541-1
disqus: forasoft

# Build settings
markdown: kramdown
paginate: 5
excerpt_separator: <!--more-->
JB :
  version : 0.3.0
BASE_PATH : http://forasoft.github.io
ASSET_PATH : false