# Site settings
title: Fora Soft
email: info@fora-soft.com
description: > # this means to ignore newlines until "baseurl:"
 Блог компании Fora Soft.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://forasoft.github.io" # the base hostname & protocol for your site
twitter_username: forasoft

footer-links:
  email: info@fora-soft.com
  facebook: ForaSoft
  github: forasoft
  instagram: fora_soft
  linkedin: fora-soft-llc-
  twitter: forasoft

google_analytics: UA-69516541-1
disqus: forasoft

# Build settings
markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables", "space_after_headers", "footnotes"]

excerpt_separator: <!--more-->
